### PR TITLE
Fixes for issues noticed while integrating v0.4.0

### PR DESCRIPTION
**Pull request by prate3k**
There were 2 issues which were identified : 

-  Component was always returning 6 weeks even though month has 4 or 5 weeks resulting in empty rows.
Screen Shot 2019-08-29 at 9 38 31 PM

-  Date highlighting doesn't work if you select the today's date as start date and some other date as end date. It wasn't highlighting in between dates.
Screen Shot 2019-08-29 at 9 39 31 PM

Approach taken : 

- For 1st issue, fix was straight forward, as we just have to compute the number of weeks current month has and pass it on while initializing array of weeks.

- For 2nd issue the fix was, it wasn't accounting for current date while deciding whether startDate is disabled or not. Adding greater than equal to check (>=) for startDate fixed the issue (basically by adding isSameDay check along with isAfterDay).

### CODE REVIEW

**Comment by vkbansal** [comment]
For date-range  selection you must use DateRangeControl. see https://github.com/vkbansal/react-date-primitives/blob/0.4.0/docs/examples/SimpleDateRangePicker.tsx

**Comment by prate3k** [comment]
Yup. We are using the same component for range selection. It internally uses `CalendarMonth` which is having that issue.

You can consider 2nd issue more of a enhancement, as source code won't have to add one extra logic explicitly to strip out empty rows. It will return the array length according to each month.

**Comment by prate3k** [comment]
@vkbansal Let me know the version number you'll publish.

**Comment by vkbansal** [comment]
0.4.2

**Comment by prate3k** [comment]
@vkbansal Should I suggest the same changes for the latest version. I see the 1st issue is still present there.

**Comment by vkbansal** [comment]
Can you share a video?

**Pull request merged**
